#!/usr/bin/env bash

DATAPATH=points_visual/
SCORETHRESH=$1
NSCORE=$2
THRESH=$3

######### Exp 2 ################
#EXPERIMENT=work_dir_py/sbr/0.3/all5/first2048/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det  --show --wait-time -1 --score-thr 0.4  --work-dir work_dir_flim/day3 --cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_one.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,5,6,7]" \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	test_dataloader.dataset.pipeline.1.transforms.2.firstk_sampling=True \
#	model.processed_points=True \
#
#
#
#EXPERIMENT=work_dir_py/sbr/0.3/all5/thresh20000_10/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det  --show --wait-time -1 --score-thr 0.15 	--work-dir work_dir_flim/day3/ 	--cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_one.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,3,5,6,7]" \
#	test_dataloader.dataset.pipeline.1.transforms.2.threshall_sampling=2. \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	model.processed_points=True \



######### Exp 14
#EXPERIMENT=work_dir_py/sbr/0.3/all5/first50000_spupdated0004_post_newfps001/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det --show --wait-time -1 --score-thr 0.45 --color-idxs -5 -5 -5 	--work-dir work_dir_flim/day3/ 	--norm-color 	--cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,4,5,6,7]" \
#	test_dataloader.dataset.pipeline.1.transforms.2.firstk_sampling=True \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	model.processed_points=True \
#	model.filter_index=4 \
#	model.neighbor_score=0.01 \


	#model.post_sort=4 \
	#model.updated_fps=1.0 \
	#model.new_fps_strat=True \





########## Exp 5 ################
# Use this for denoising
#EXPERIMENT=work_dir_py/sbr/0.3/all5/first2048/
#EXPERIMENT=work_dir_py/sbr/0.3/all5/first50000_spupdated0004_post_newfps001/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det  --show --wait-time -1 --score-thr 0.25  --work-dir work_dir_flim/day3/ --cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_one.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,5,6,7]" \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	test_dataloader.dataset.pipeline.1.transforms.2.firstk_sampling=True \
#	model.processed_points=True \

#EXPERIMENT=work_dir_py/sbr/0.3/all5/first2048/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det  --show --wait-time -1 --score-thr 0.35  --work-dir work_dir_flim/day3 --cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_one.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,5,6,7]" \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	test_dataloader.dataset.pipeline.1.transforms.2.firstk_sampling=True \
#	model.processed_points=True \
#
#
#
#EXPERIMENT=work_dir_py/sbr/0.3/all5/thresh20000_10/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det  --show --wait-time -1 --score-thr 0.45 \
#	--work-dir work_dir_flim/day3/ \
#	--cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_one.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,3,5,6,7]" \
#	test_dataloader.dataset.pipeline.1.transforms.2.threshall_sampling=3. \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	model.processed_points=True \
#
#
#EXPERIMENT=work_dir_py/sbr/0.3/all5/first50000_spupdated0004_post_newfps001/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det --show --wait-time -1 --score-thr 0.45 --color-idxs -5 -5 -5 \
#	--work-dir work_dir_flim/day3/ \
#	--norm-color \
#	--cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_one.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,3,4,5,6,7]" \
#	test_dataloader.dataset.pipeline.1.transforms.2.firstk_sampling=True \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	model.processed_points=True \
#	model.filter_index=4 \
#	model.neighbor_score=0.2 \
#	model.post_sort=4 \
#	model.updated_fps=3. \
#	model.new_fps_strat=True \



#### day 4 exp 14 10s
## Use this for denoising after copying the file to 000001.bin
#EXPERIMENT=work_dir_py/sbr/0.3/all5/first2048/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det  --show --wait-time -1 --score-thr 0.5  --work-dir work_dir_flim/day4/ --cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_one.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,5,6,7]" \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	test_dataloader.dataset.pipeline.1.transforms.2.firstk_sampling=True \
#	model.processed_points=True \

#EXPERIMENT=work_dir_py/sbr/0.3/all5/first2048/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det  --show --wait-time -1 --score-thr 0.4  --work-dir work_dir_flim/day4/ --cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_one.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,5,6,7]" \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	test_dataloader.dataset.pipeline.1.transforms.2.firstk_sampling=True \
#	model.processed_points=True \
#
#
#
#EXPERIMENT=work_dir_py/sbr/0.3/all5/thresh20000_10/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det  --show --wait-time -1 --score-thr 0.25 \
#	--work-dir work_dir_flim/day4/ \
#	--cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_one.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,3,5,6,7]" \
#	test_dataloader.dataset.pipeline.1.transforms.2.threshall_sampling=3. \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	model.processed_points=True \
#
#EXPERIMENT=work_dir_py/sbr/0.3/all5/first50000_spupdated0004_post_newfps001/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det --show --wait-time -1 --score-thr 0.45 --color-idxs -5 -5 -5 \
#	--work-dir work_dir_flim/day4/ \
#	--norm-color \
#	--cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_one.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,3,4,5,6,7]" \
#	test_dataloader.dataset.pipeline.1.transforms.2.firstk_sampling=True \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	model.processed_points=True \
#	model.filter_index=4 \
#	model.neighbor_score=0.25 \


#### day 4 exp19 10s
# Use this for denoising
#EXPERIMENT=work_dir_py/sbr/0.3/all5/first50000_spupdated0004_post_newfps001/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det  --show --wait-time -1 --score-thr 0.16  --work-dir work_dir_flim/day4/ --cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_one.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,5,6,7]" \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	test_dataloader.dataset.pipeline.1.transforms.2.firstk_sampling=True \
#	model.processed_points=True \


#EXPERIMENT=work_dir_py/sbr/0.3/all5/first2048/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det  --show --wait-time -1 --score-thr 0.3  --work-dir work_dir_flim/day4/ --cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_one.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,5,6,7]" \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	test_dataloader.dataset.pipeline.1.transforms.2.firstk_sampling=True \
#	model.processed_points=True \
#


#EXPERIMENT=work_dir_py/sbr/0.3/all5/thresh20000_10/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det  --show --wait-time -1 --score-thr 0.25 \
#	--work-dir work_dir_flim/day4/ \
#	--cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_one.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,3,5,6,7]" \
#	test_dataloader.dataset.pipeline.1.transforms.2.threshall_sampling=5. \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	model.processed_points=True \
#
#
#
#
#EXPERIMENT=work_dir_py/sbr/0.3/all5/first50000_spupdated0004_post_newfps001/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det --show --wait-time -1 --score-thr 0.45 --color-idxs -5 -5 -5 \
#	--work-dir work_dir_flim/day4/ \
#	--norm-color \
#	--cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_one.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,3,4,5,6,7]" \
#	test_dataloader.dataset.pipeline.1.transforms.2.firstk_sampling=True \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	model.processed_points=True \
#	model.filter_index=4 \
#	model.neighbor_score=0.25 \
#


# day 5 exp 18, set nms to 0.001 in configs/_base_/models/votenet.py 
## Use this for denoising
#EXPERIMENT=work_dir_py/sbr/0.3/all5/first50000_spupdated0004_post_newfps001/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det  --show --wait-time -1 --score-thr 0.16  --work-dir work_dir_flim/day5/ --cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_one.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,5,6,7]" \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	test_dataloader.dataset.pipeline.1.transforms.2.firstk_sampling=True \
#	model.processed_points=True \


#EXPERIMENT=work_dir_py/sbr/0.3/all5/first2048/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det  --show --wait-time -1 --score-thr 0.15  --work-dir work_dir_flim/day5/ --cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_one.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,5,6,7]" \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	test_dataloader.dataset.pipeline.1.transforms.2.firstk_sampling=True \
#	model.processed_points=True \
#
#
#EXPERIMENT=work_dir_py/sbr/0.3/all5/thresh20000_10/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det  --show --wait-time -1 --score-thr 0.375 \
#	--work-dir work_dir_flim/day5/ \
#	--cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_one.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,3,5,6,7]" \
#	test_dataloader.dataset.pipeline.1.transforms.2.threshall_sampling=3. \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	model.processed_points=True \
#
#
#EXPERIMENT=work_dir_py/sbr/0.3/all5/first50000_spupdated0004_post_newfps001/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det --show --wait-time -1 --score-thr 0.375 --color-idxs -5 -5 -5 \
#	--work-dir work_dir_flim/day5/ \
#	--norm-color \
#	--cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_one.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,3,4,5,6,7]" \
#	test_dataloader.dataset.pipeline.1.transforms.2.firstk_sampling=True \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	model.processed_points=True \
#	model.filter_index=4 \
#	model.neighbor_score=0.2 \






#### day 5 exp 6, set nms to 0.001 in configs/_base_/models/votenet.py 
## Use this for denoising
#EXPERIMENT=work_dir_py/sbr/0.3/all5/first50000_spupdated0004_post_newfps001/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det  --show --wait-time -1 --score-thr 0.2  --work-dir work_dir_flim/day5/ --cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_one.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,5,6,7]" \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	test_dataloader.dataset.pipeline.1.transforms.2.firstk_sampling=True \
#	model.processed_points=True \


#EXPERIMENT=work_dir_py/sbr/0.3/all5/first2048/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det  --show --wait-time -1 --score-thr 0.4  --work-dir work_dir_flim/day5/ --cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_one.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,5,6,7]" \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	test_dataloader.dataset.pipeline.1.transforms.2.firstk_sampling=True \
#	model.processed_points=True \
#
#
#EXPERIMENT=work_dir_py/sbr/0.3/all5/thresh20000_10/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#EXPERIMENT=work_dir_py/sbr/0.3/all5/first50000_spupdated0004_post_newfps001/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det  --show --wait-time -1 --score-thr 0.5 \
#	--work-dir work_dir_flim/day5/ \
#	--cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_one.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,3,5,6,7]" \
#	test_dataloader.dataset.pipeline.1.transforms.2.threshall_sampling=5. \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	model.processed_points=True \
#
#
#
#EXPERIMENT=work_dir_py/sbr/0.3/all5/first50000_spupdated0004_post_newfps001/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det --show --wait-time -1 --score-thr 0.32 --color-idxs -5 -5 -5 \
#	--work-dir work_dir_flim/day5/ \
#	--norm-color \
#	--cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_one.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,3,4,5,6,7]" \
#	test_dataloader.dataset.pipeline.1.transforms.2.firstk_sampling=True \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	model.processed_points=True \
#	model.filter_index=4 \
#	model.neighbor_score=1.0 \





### day 5 exp 11, set nms to 0.001 in configs/_base_/models/votenet.py 
## Use this for denoising
#EXPERIMENT=work_dir_py/sbr/0.3/all5/first50000_spupdated0004_post_newfps001/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det  --show --wait-time -1 --score-thr 0.2  --work-dir work_dir_flim/day5/ --cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_one.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,5,6,7]" \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	test_dataloader.dataset.pipeline.1.transforms.2.firstk_sampling=True \
#	model.processed_points=True \


#EXPERIMENT=work_dir_py/sbr/0.3/all5/first2048/
#EXPERIMENT=work_dir_py/sbr/0.3/all5/thresh20000_10/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det  --show --wait-time -1 --score-thr 0.4  --work-dir work_dir_flim/day5/ --cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_one.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,5,6,7]" \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	test_dataloader.dataset.pipeline.1.transforms.2.firstk_sampling=True \
#	model.processed_points=True \
#
#
#EXPERIMENT=work_dir_py/sbr/0.3/all5/thresh20000_10/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det  --show --wait-time -1 --score-thr 0.21 \
#	--work-dir work_dir_flim/day5/ \
#	--cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_one.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,3,5,6,7]" \
#	test_dataloader.dataset.pipeline.1.transforms.2.threshall_sampling=3. \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	model.processed_points=True \
#
#
#
#EXPERIMENT=work_dir_py/sbr/0.3/all5/first50000_spupdated0004_post_newfps001/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det --show --wait-time -1 --score-thr 0.4 --color-idxs -5 -5 -5 \
#	--work-dir work_dir_flim/day5/ \
#	--norm-color \
#	--cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_one.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,3,4,5,6,7]" \
#	test_dataloader.dataset.pipeline.1.transforms.2.firstk_sampling=True \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	model.processed_points=True \
#	model.filter_index=4 \
#	model.neighbor_score=0.1 \


IFS=', ' read -r -a NSCOREALL <<< $NSCORE
for NSCORECURR in "${NSCOREALL[@]}"
do

#day 10
EXPERIMENT=work_dir_py/sbr/0.3/joint/first50000_spupdatedX_post_newfps001/first50000_spupdated0003_post_newfps001/
CHECKPOINT=${EXPERIMENT}/epoch_12.pth
CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
	--show-dir outimages  --task lidar_det --show --wait-time 0.5 --score-thr $SCORETHRESH --color-idxs -5 -5 -5 \
	--work-dir work_dir_flim/ppc_${NSCORECURR}_${SCORETHRESH} \
	--norm-color \
	--cfg-options \
	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
	test_dataloader.dataset.ann_file='sunrgbd_infos_val.pkl' \
	test_dataloader.dataset.pipeline.0.load_dim=8 \
	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,3,4,5,6,7]" \
	test_dataloader.dataset.pipeline.1.transforms.2.firstk_sampling=True \
	test_dataloader.dataset.pipeline.1.transforms.2.num_points=100000 \
	model.processed_points=True \
	model.filter_index=5 \
	model.neighbor_score=$NSCORECURR \

       
done




EXPERIMENT=work_dir_py/sbr/0.3/all5/first2048/
EXPERIMENT=work_dir_py/sbr/0.3/joint/thresh/thresh50000_10/
CHECKPOINT=${EXPERIMENT}/epoch_12.pth
CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
	--show-dir outimages  --task lidar_det  --show --wait-time 0.5 --score-thr $SCORETHRESH  --work-dir work_dir_flim/points100000_$SCORETHRESH --cfg-options \
	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
	test_dataloader.dataset.ann_file='sunrgbd_infos_val.pkl' \
	test_dataloader.dataset.pipeline.0.load_dim=8 \
	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,5,6,7]" \
	test_dataloader.dataset.pipeline.1.transforms.2.num_points=100000 \
	test_dataloader.dataset.pipeline.1.transforms.2.firstk_sampling=True \
	model.processed_points=True \




IFS=', ' read -r -a THRESHALL <<< $THRESH
for THRESHCURR in "${THRESHALL[@]}"
do

EXPERIMENT=work_dir_py/sbr/0.3/joint/thresh/thresh50000_10/
CHECKPOINT=${EXPERIMENT}/epoch_12.pth
CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
	--show-dir outimages  --task lidar_det  --show --wait-time 0.5 --score-thr $SCORETHRESH \
	--work-dir work_dir_flim/thresh${THRESHCURR}_$SCORETHRESH \
	--cfg-options \
	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
	test_dataloader.dataset.ann_file='sunrgbd_infos_val.pkl' \
	test_dataloader.dataset.pipeline.0.load_dim=8 \
	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,3,5,6,7]" \
	test_dataloader.dataset.pipeline.1.transforms.2.threshall_sampling=$THRESHCURR \
	test_dataloader.dataset.pipeline.1.transforms.2.num_points=100000 \
	model.processed_points=True \


done


