#!/usr/bin/env bash
#SBATCH --partition=research
#SBATCH --cpus-per-task=2
#SBATCH --mem=36G
#SBATCH --time=1:0:0
#SBATCH -o plotlogs/slurm.%j.%N.out # STDOUT
#SBATCH -e plotlogs/slurm.%j.%N.err # STDERR
#SBATCH --job-name=plotmmdt

module load anaconda/mini/23.3.1
bootstrap_conda
conda activate openmmlab

#cd work_dir_py/cf-wsp/
#cd work_dir_py/npeakswogtvalid/
#cd work_dir_py/npeaks/
cd work_dir_py/sbr/
#cd work_dir_py/gaussfilternpeaks/
#cd work_dir_py/npeaks/
#cd work_dir_py/cf-wsp/1_50/updated/
#cd work_dir_py/baselines/argmax_filtering/
#cd work_dir_py/baselines/
#cd work_dir_py/compression/

#python ../../../tools/analysis_tools/analyze_logs.py plot_curve updated/fps5000_sp01_post  updated/fps5000_wsp0{02,05,1}*  --eval --out out.pdf
#python ../../../tools/analysis_tools/analyze_logs.py plot_curve 1_100/top*  --eval --out out.pdf
#python ../../../tools/analysis_tools/analyze_logs.py plot_curve */points*  --eval --out points.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve 5_100/updated/fps30000_sp02_post_set-1000  5_100/updated/fps{5,10,20,30,40}000_sp01_post_set-1000  --eval --out out.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve 5_50/updated/fps{20,30,40}000_sp01_post_set-1000*  --eval --keys mAP_0.25  --out out.pdf



#python ../../tools/analysis_tools/analyze_logs.py plot_curve 5_50/updated/fps{5,10,20,30,40}000_sp01_post_set-1000  --eval --keys mAP_0.25 mAP_0.50 --out out.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve 1_50/updated/sp0*_post*  --eval --out out.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve {5_50,5_100}/updated/fps*000_sp01_post_set-1000  --eval --out out.pdf
#python ../../../tools/analysis_tools/analyze_logs.py plot_curve 1_50/points*  --eval --out out.pdf


#python ../../tools/analysis_tools/analyze_logs.py plot_curve */updated/fps5000_sp01_post_set-1000 */updated/sp01 --eval --out out.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve */updated/fps5000_sp01_post_set-1000 */updated/sp01_post  --eval --out out.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve */updated/fps5000_sp01_post_set-1000 */updated/fps5000_post  --eval --out ablationwfiltering.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve 5_50/updated/fps30000_sp01_post_set-1000 5_50/updated/fps30000_post 5_100/updated/fps30000_sp01_post_set-1000  --eval --out ablationwfiltering.pdf




#
#
#
#
#
#
#
#
#
#
#
#
#python ../../tools/analysis_tools/analyze_logs.py plot_curve 1_50/updated/fps5000_post*  --eval --out out.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve 1_50/updated/fps5000_{wsp005_post,wsp0075_post,wsp01_post,wsp0125_post,wsp015_post,wsp01_postwsp,wsp0075_postwsp,sp01_post,sp01_post_set-1000}  --eval --out out.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve 1_50/updated/fps5000_sp01_pos{t,t_set-1000,t_featsp,t_featspbaseline,t_featsp_attnmask} --eval --out out.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve 3dcnndenoise-{softmax,argmax}/denoise/1_50/points*  --eval --out out.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve 1_50/updated/{fps5000_s,s}p01_post  1_50/updated/fps5000_sp01_post_updatedfps{03,04,05,06,07}  --eval --keys mAP_0.25 mAR_0.25 --out out.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve all4/updated/sp01_post_updatedfps05_e12 */updated/sp01_post_updatedfps05 ../baselines/argmax_filtering/all4/points*_e12 --eval --keys mAP_0.25 mAR_0.25 --out out.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve 32/argmax/*/points2048 32/cf-wsp/*/sp01_post_updatedfps05 --eval --out out.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve ../baselines/argmax_filtering_allprob1/1_50/{sp03,sp03_post_updatedfps05} 1_50/updated/sp01_post_updatedfps05 --eval --keys mAP_0.50 mAR_0.50 chair_AP_0.50 chair_rec_0.50 --out out.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve 1peak/1_50/{points2048,first2048,first10000_sp01_post_updatedfps05} 2peak/1_50/first{4096,20000}_sp01_post_updatedfps05 3peak/1_50/first30000_sp01_post_updatedfps05  --eval --out out.pdf

#python ../../tools/analysis_tools/analyze_logs.py plot_curve rerun/1peak/5_50/first10000 rerun/1peak/5_50/first10000_spupdated01_post_updatedfps05 rerun/2peak/5_50/first20000_spupdated01_post_updatedfps05   --eval --keys mAP_0.50 mAR_0.50 --out 5_50.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve rerun/1peak/5_50/first10000 rerun/1peak/5_50/first20000_spupdated01_post_updatedfps05 rerun/2peak/5_50/first40000_spupdated01_post_updatedfps05   --eval --keys mAP_0.50 mAR_0.50 --out 5_50_more.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve rerun/1peak/1_50/first2048 rerun/1peak/1_50/first10000_spupdated01_post_updatedfps05 rerun/2peak/1_50/first20000_spupdated01_post_updatedfps05  --eval --keys mAP_0.25 mAR_0.25 --out 1_50.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve rerun/1peak/1_50/first2048 rerun/1peak/1_50/first20000_spupdated01_post_updatedfps05 rerun/2peak/1_50/first50000_spupdated01_post_updatedfps05  --eval --keys mAP_0.25 mAR_0.25 --out 1_50_more.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve rerun/1peak/1_50/first50000_spupdated03_post_updatedfps05 rerun/1peak/1_50/first50000_cfupdated02_post_updatedfpscf05_repeat --eval --keys mAP_0.25 --out 1_50_cf.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve rerun/1peak/1_50/first50000_spupdated03_post_updatedfps05* rerun/1peak/1_50/first50000_cfupdated0{1,2}_post_updatedfpscf05* --eval --keys mAP_0.25 --out 1_50_feat.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve rerun/1peak/1_50/first50000_spupdated03_post_updatedfps05 rerun/1peak/1_50/first50000_cfupdated02_post_updatedfpscf05 --eval --keys mAP_0.25 --out 1_50_feat.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve min2/1peak/1_50/first*  --eval --keys mAP_0.25 --out 1_50_min2_1peak.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve min2/2peak/1_50/*spupdated01_*fps06* min2/2peak/1_50/*_{w,wo}shuffle   --eval --keys mAP_0.25 --out 1_50_min2_2peak.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve ../gaussfilternpeaks/min2/1peak/1_50/first50000_spupdated02_post_updatedfps05 min2/1peak/1_50/first50000_spupdated02_post_newfps05  ../gaussfilternpeaks/min2/2peak/1_50/first50000_spupdated01_post_updatedfps05 min2/2peak/1_50/first50000_spupdated01_post_newfps06  min2_allpeaks/2peak/1_50/first50000_spupdated01_post_newfps06*    --eval --keys mAP_0.25 --out 1_50_peakcomp.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve ../gaussfilternpeaks/min2/*peak/1_50/first50000_spupdated0*_post_updatedfps0* ../gaussfilternpeaks/min2/1peak/1_50/thresh*   --eval --keys mAP_0.25 --out 1_50_gaussfilternpeaks.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve min2/2peak/*_*/first50000_spupdated01_post_newfps06 min2/1peak/*_*/first50000_spupdated02_post_newfps05  ../baselines/argmax-filtering/min2/*_*/thresh20000_10  --eval --keys mAP_0.25 --out bigcomp_individual.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve min2/2peak/all4/first50000_spupdated01_post_newfps06 min2/1peak/all4/first50000_spupdated02_post_newfps05  ../baselines/argmax-filtering/min2/all4/thresh20000_10  --eval --keys mAP_0.25 --out bigcomp.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve ../baselines/argmax-filtering/min2/*/thresh20000_10  ../baselines/argmax-filtering/min2/1_50/{06/*,09/*,10/*,125/*,15/*}  --eval --keys mAP_0.25 --out 1_50_min2_thresh.pdf

#python ../../tools/analysis_tools/analyze_logs.py plot_curve *peak/1_50/first{2048,4096,6144}_sp01_post_updatedfps05  --eval --keys mAP_0.25 mAR_0.25 --out out.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve 3peak/1_50/first30000_s{p,pupdated}01_post_updated*fps05*  --eval --out out.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve 1_50/updated/sp01_post_updatedfps0{5_repeat,5_repeat2} 1_50/updated/s{p,pmin,pmax}updated01_post_updatedfps05 1_50/updated/spupdated01_post_updatedminfps05 1_50/updated/spmedian01_post_updatedfps05  --eval --keys mAP_0.25 --out out.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve 5_50/updated/sp01_post_updatedfps0{5_repeat,5_repeat2} 5_50/updated/s{p,pmin,pmax}updated01_post_updatedfps05 5_50/updated/spupdated01_post_updatedminfps05 5_50/updated/spmedian01_post_updatedfps05  --eval --keys mAP_0.25 --out out.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve *_*/updated/spmedian01_post_updatedfps05 *_*/updated/sp01_post_updatedfps0{5,5_latest}   --eval --keys mAP_0.25 --out out.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve {5_50,1_50}/rerun/s{p,pupdated}01_post_updatedfps05   --eval --keys mAP_0.25 mAR_0.25 --out out.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve ../../baselines/gtdepth/points* --eval --keys mAP_0.25 mAP_0.50 --out out.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve *peak/1_50/first* --eval --keys mAP_0.25 mAP_0.50 --out out.pdf
#
#
#
#
#python ../../tools/analysis_tools/analyze_logs.py plot_curve 1_50/first*  --eval --keys mAP_0.25 --out 1_50.pdf
python ../../tools/analysis_tools/analyze_logs.py plot_curve 0.3/all5/*  --eval --keys mAP_0.25 --out 0.3.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve 0.3/*_*/*  --eval --keys mAP_0.25 --out 0.3_individual.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve 1.0/all5/*  --eval --keys mAP_0.25 --out 1.0.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve 1.0/*_*/*  --eval --keys mAP_0.25 --out 1.0_individual.pdf

#python ../../tools/analysis_tools/analyze_logs.py plot_curve 0.048/*_*/first50000_spupdated0001* 0.048/*_*/thresh*  --eval --keys mAP_0.25 --out 0.048_individual.pdf
#python ../../tools/analysis_tools/analyze_logs.py plot_curve 0.048/all5/*  --eval --keys mAP_0.25 --out 0.048.pdf

python ../../tools/analysis_tools/analyze_logs.py plot_curve ../gaussian_noise/*/*  --eval --keys mAP_0.25 --out gaussian_noise.pdf

python ../../tools/analysis_tools/analyze_logs.py plot_curve 1.0/score-denoised_sunrgbd*/*_*/*  --eval --keys mAP_0.25 --out score_denoise.pdf



