#!/usr/bin/env bash
#SBATCH --partition=research
#SBATCH --cpus-per-task=4
#SBATCH --gres=gpu:1
#SBATCH --mem=24000
#SBATCH --time=24:0:0
###SBATCH --nodelist=euler19
#SBATCH --exclude=euler05,euler24,euler25,euler26,euler27
#SBATCH -o slurm.%j.%N.out # STDOUT
#SBATCH -e slurm.%j.%N.err # STDERR
#SBATCH --job-name=testmmdt3d
###SBATCH --no-requeue

module load anaconda/mini/23.3.1
module load nvidia/cuda/11.8.0
bootstrap_conda
conda activate openmmlab
export CUDA_HOME=/opt/apps/cuda/x86_64/11.8.0/default


CHECKPOINT=checkpoints/votenet_16x8_sunrgbd-3d-10class_20210820_162823-bf11f014.pth
CHECKPOINT=checkpoints/hv_pointpillars_secfpn_6x8_160e_kitti-3d-car_20220331_134606-d42d15ed.pth
EXPERIMENT=work_dir_py/sbr/0.3/all5/thresh20000_10/
EXPERIMENT=work_dir_py/sbr/0.3/all5/first2048/
EXPERIMENT=work_dir_py/sbr/0.3/all5/first50000_spupdated0004_post_newfps001_fixedrepeat/
#EXPERIMENT=work_dir_py/sbr/0.3/all5/first50000_spupdated02_post_finfps001_unitprobs/
#_post_newfps001/
#EXPERIMENT=work_dir_py/sbr/1.0/score-denoised_sunrgbd1000fastfast/all5/point20000/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
DATAPATH=points_clean8/


SBR=("clean" "5_50" "5_100" "1_50" "1_100")
#for i in "${!SBR[@]}"
#do
#DATAPATH=points_min2/0.3/argmax-filtering-sbr/${SBR[$i]}/

#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} --cfg-options \
CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/pointpillars/pointpillars_hv_secfpn_8xb6-160e_kitti-3d-car.py ${CHECKPOINT}


# --cfg-options \
#	work_dir=mapresults/work_dirs_sp0004_newfps001_fixedrepeat \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,4,5,6,7]" \
#	model.neighbor_score=0.004 \
#	model.filter_index=4 \
#	model.post_sort=4 \
#	model.updated_fps=0.01 \


#done

	#test_dataloader.dataset.pipeline.1.transforms.2.thresh_sampling=1.0 \
	#test_dataloader.dataset.pipeline.1.transforms.2.firstk_sampling=True \
	#test_dataloader.dataset.pipeline.0.unit_probabilities=True \

