#!/usr/bin/env bash
#SBATCH --partition=research
#SBATCH --cpus-per-task=4
#SBATCH --gres=gpu:1
#SBATCH --mem=20000
#SBATCH --time=96:0:0
###SBATCH --nodelist=euler19
###SBATCH --exclude=euler01,euler02,euler03
#SBATCH -o slurm.%j.%N.out # STDOUT
#SBATCH -e slurm.%j.%N.err # STDERR
#SBATCH --job-name=mmdt3d
###SBATCH --no-requeue

module load anaconda/mini/23.3.1
module load nvidia/cuda/11.8.0
bootstrap_conda
conda activate openmmlab

CHECKPOINT=checkpoints/votenet_16x8_sunrgbd-3d-10class_20210820_162823-bf11f014.pth
EXPERIMENT=./work_dir_py/5_10_peaks/votenet_8xb16_sunrgbd-3d/
#EXPERIMENT=./work_dir_py/5_50_argmax/votenet_8xb16_sunrgbd-3d/
CHECKPOINT=${EXPERIMENT}/epoch_36.pth
DATAPATH=py/points_5_10_peaks

CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} --cfg-options \
	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \


#	test_dataloader.dataset.pipeline.0.load_dim=7 \

	
#test_dataloader.dataset.pipeline.1.transforms.2.num_points=10000 \

#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,3]" \
#	model.backbone.in_channels=5 \






 
