#!/usr/bin/env bash
#SBATCH --partition=research
#SBATCH --cpus-per-task=4
#SBATCH --gres=gpu:1
#SBATCH --mem=20000
#SBATCH --time=96:0:0
###SBATCH --nodelist=euler19
#SBATCH --exclude=euler01,euler02,euler04,euler05,euler20,euler21,euler24,euler25,euler26,euler27
#SBATCH -o slurm.%j.%N.out # STDOUT
#SBATCH -e slurm.%j.%N.err # STDERR
#SBATCH --job-name=testmmdt3d
###SBATCH --no-requeue

module load anaconda/mini/23.3.1
module load nvidia/cuda/11.8.0
bootstrap_conda
conda activate openmmlab

CHECKPOINT=checkpoints/votenet_16x8_sunrgbd-3d-10class_20210820_162823-bf11f014.pth
#EXPERIMENT=./work_dir_py/5_10_peaks/votenet_8xb16_sunrgbd-3d/
EXPERIMENT=work_dir_py/cf-wsp/1_100/updated/fps5000_sp01_post_set-1000
EXPERIMENT=work_dir_py/cf-wsp/all4/updated/sp01_post_updatedfps05_e12
EXPERIMENT=work_dir_py/baselines/argmax_filtering/all4/points2048_e12
#EXPERIMENT=./work_dir_py/5_50_argmax/votenet_8xb16_sunrgbd-3d/
CHECKPOINT=${EXPERIMENT}/epoch_12.pth
DATAPATH=wsp_cf/peaks-confidence_5_50
DATAPATH=points_baseline/argmax-filtering-conf/5_50/

CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} --cfg-options \
	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
	test_dataloader.dataset.pipeline.0.load_dim=7 \
	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,4]" \
	model.backbone.in_channels=4 \




	#model.filter_index=4 \
	#model.post_sort=4 \
	#model.neighbor_score=0.1 \
	#model.updated_fps=0.5 \
	#model.backbone.fps_sample_range_list="[5000,-1,-1,-1]" \





 
