#!/usr/bin/env bash
CHECKPOINT=checkpoints/votenet_16x8_sunrgbd-3d-10class_20210820_162823-bf11f014.pth
DATAPATH=points_clean8/

EXPERIMENT=work_dir_py/sbr/0.3/joint/first50000_spupdated0004_post_newfps001/
EXPERIMENT=work_dir_py/sbr/0.3/joint/first50000_spupdatedX_post_newfps001/first50000_spupdated0003_post_newfps001/
EXPERIMENT=work_dir_py/sbr/0.3/joint/first50000_spupdatedX/first50000_spupdated0003/
CHECKPOINT=${EXPERIMENT}/epoch_12.pth
SBR=5_50
DATAPATH=points_min2/0.3/argmax-filtering-sbr/${SBR}/

SBR=5_100
DATAPATH=training/points8192_r025_dist10/0.3/argmax-filtering-sbr/${SBR}/

# color idxs is -4 for prob and -3 -2 -1 for rgb
# if using filtering, then -5 and -4 -3 -2 for rgb

#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det --show --wait-time 0.5 --score-thr 0.5 --color-idxs -4 -3 -2 \
#	--work-dir work_dir_vis/${SBR} \
#	--cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_mediumvis.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,4,5,6,7]" \
#	test_dataloader.dataset.pipeline.1.transforms.2.firstk_sampling=True \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	model.processed_points=True \
#	model.filter_index=4 \
#	model.neighbor_score=0.003 \


	#--norm-color \
	#model.updated_fps=0.01 \
	#model.post_sort=4 \


#EXPERIMENT=work_dir_py/sbr/0.3/joint/thresh/thresh50000_10/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det  --show --wait-time 0.5 --score-thr 0.5  \
#	--work-dir work_dir_vis/${SBR}_thresh50000_10 \
#	--cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_mediumvis.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,3,5,6,7]" \
#	test_dataloader.dataset.pipeline.1.transforms.2.thresh_sampling=1.0 \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	model.processed_points=True \


#EXPERIMENT=work_dir_py/sbr/0.3/joint/point2048/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det  --show --wait-time 0.5 --score-thr 0.5 --load-pts-again \
#	--work-dir work_dir_vis/${SBR}_argmax \
#	--cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_mediumvis.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,5,6,7]" \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=2048 \
#	model.processed_points=True \




## replace this for gt boxes as well
#CHECKPOINT=checkpoints/votenet_16x8_sunrgbd-3d-10class_20210820_162823-bf11f014.pth
#DATAPATH=points_clean8/
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det  --show --wait-time 0.5 --score-thr 0.5 \
#	--work-dir work_dir_vis/clean \
#	--cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_mediumvis.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,5,6,7]" \
#	model.processed_points=True \
#	test_dataloader.dataset.pipeline.2.transforms.2.num_points=50000 \
#	test_dataloader.dataset.pipeline.2.transforms.2.firstk_sampling=True \


#EXPERIMENT=work_dir_py/sbr/1.0/score-denoised_sunrgbd1000fastfast/${SBR}/point20000
#EXPERIMENT=work_dir_py/sbr/0.3/joint/thresh50000_10/
#CHECKPOINT=${EXPERIMENT}/epoch_12.pth
#DATAPATH=points_min2/1.0/score-denoised_sunrgbd1000fastfast/argmax-filtering-sbr/${SBR}/pcl/
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
#	--show-dir outimages  --task lidar_det  --show --wait-time 0.5 --score-thr 0.5  \
#	--work-dir work_dir_vis/large/${SBR}_score \
#	--cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='sunrgbd_infos_val_mediumvis.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=8 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,3,4,5,6,7]" \
#	test_dataloader.dataset.pipeline.0.unit_probabilities=True \
#	test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
#	model.processed_points=True \





####################### KITTI ########################
#EXPERIMENT=work_dir_py/kitti/pvrcnn/3class/joint/0.3/npupdated00002/
#CHECKPOINT=${EXPERIMENT}/epoch_10.pth
#
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/pv_rcnn/pv_rcnn_8xb2-80e_kitti-3d-3class.py ${CHECKPOINT}  \
#	--show-dir outimages  --task lidar_det --show --wait-time 0.1 --score-thr 0.6 --color-idxs -1 -1 -1 \
#	--norm-color \
#	--work-dir work_dir_vis/ppc_${SBR} \
#	--cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.pipeline.0.load_dim=6 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,5,4]" \
#	test_dataloader.dataset.ann_file='kitti_infos_val_mediumvis.pkl' \
#	test_evaluator.ann_file='data/kitti/kitti_infos_val_mediumvis.pkl' \
#	model.data_preprocessor.in_channels=4 \
#	model.data_preprocessor.post=True \
#	model.data_preprocessor.neighbor_score=0.0002 \
#	model.data_preprocessor.filter_index=4 \
#	model.processed_points=True \
#
#
#	#model.updated_fps=0.01 \
#	#model.post_sort=4 \
#
#
#
#EXPERIMENT=work_dir_py/kitti/pvrcnn/3class/joint/0.3/baseline/
#CHECKPOINT=${EXPERIMENT}/epoch_10.pth
#
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/pv_rcnn/pv_rcnn_8xb2-80e_kitti-3d-3class.py ${CHECKPOINT}  \
#	--show-dir outimages  --task lidar_det --show --wait-time 0.1 --score-thr 0.6 \
#	--no-color \
#	--work-dir work_dir_vis/points_${SBR} \
#	--cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.pipeline.0.load_dim=6 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,5]" \
#	test_dataloader.dataset.ann_file='kitti_infos_val_mediumvis.pkl' \
#	test_evaluator.ann_file='data/kitti/kitti_infos_val_mediumvis.pkl' \
#	model.data_preprocessor.in_channels=4 \
#	model.processed_points=True \
#


## requres chanigng config file for sampling with thresholding
#
#EXPERIMENT=work_dir_py/kitti/pvrcnn/3class/joint/0.3/baseline/
#CHECKPOINT=${EXPERIMENT}/epoch_10.pth
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/pv_rcnn/pv_rcnn_8xb2-80e_kitti-3d-3class.py ${CHECKPOINT}  \
#	--show-dir outimages  --task lidar_det --show --wait-time 0.1 --score-thr 0.6 \
#	--no-color \
#	--work-dir work_dir_vis/thresh075_${SBR} \
#	--cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.pipeline.0.load_dim=6 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,5,3]" \
#	test_dataloader.dataset.ann_file='kitti_infos_val_mediumvis.pkl' \
#	test_evaluator.ann_file='data/kitti/kitti_infos_val_mediumvis.pkl' \
#	model.data_preprocessor.in_channels=4 \
#	model.processed_points=True \
#	test_dataloader.dataset.pipeline.1.thresh_index=4 \
#	test_dataloader.dataset.pipeline.1.threshall_sampling=0.75 \





## replace this for gt boxes as well
#CHECKPOINT=checkpoints/pv_rcnn_8xb2-80e_kitti-3d-3class_20221117_234428-b384d22f.pth
#DATAPATH=training/velodyne_reduced6/
#CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/pv_rcnn/pv_rcnn_8xb2-80e_kitti-3d-3class.py ${CHECKPOINT}  \
#	--show-dir outimages  --task lidar_det --show --wait-time 0.1 --score-thr 0.6 \
#	--work-dir work_dir_vis/gt \
#	--no-color \
#	--cfg-options \
#	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
#	test_dataloader.dataset.ann_file='kitti_infos_val_mediumvis.pkl' \
#	test_evaluator.ann_file='data/kitti/kitti_infos_val_mediumvis.pkl' \
#	test_dataloader.dataset.pipeline.0.load_dim=6 \
#	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,5]" \
#	model.data_preprocessor.in_channels=4 \
#	model.processed_points=True \
#
#
##	--load-pts-again \



#CUDA_VISIBLE_DEVICES=0 python -u demo/pcd_demo.py demo/data/sunrgbd/000017.bin configs/votenet/votenet_8xb16_sunrgbd-3d.py checkpoints/votenet_16x8_sunrgbd-3d-10class_20210820_162823-bf11f014.pth  --show --out-dir outimages_gt --cfg-options test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,3,4,5]"  \


	#test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \



# Change loading.py, dataset config, tools/test.py drawgt flag, in bfile change pipleine.1 to pipeline.2
# change wait time to 2.0 to see 20 views


