#!/usr/bin/env bash
CHECKPOINT=checkpoints/votenet_16x8_sunrgbd-3d-10class_20210820_162823-bf11f014.pth
EXPERIMENT=work_dir_py/sbr/0.3/all5/first2048/
EXPERIMENT=work_dir_py/sbr/0.3/all5/thresh20000_10/
EXPERIMENT=work_dir_py/sbr/0.3/all5/first50000_spupdated0004_post_newfps001/
CHECKPOINT=${EXPERIMENT}/epoch_12.pth

DATAPATH=points_min2/0.3/argmax-filtering-sbr/1_50/
DATAPATH=points_clean8/

# test.py reads pcd again for visualization, so testing augmentations are not applied
CUDA_VISIBLE_DEVICES=0 python -u tools/test.py configs/votenet/votenet_8xb16_sunrgbd-3d.py ${CHECKPOINT} \
	--show-dir outimages  --task lidar_det --show --wait-time 0.5 --score-thr 0.5 \
	--cfg-options \
	test_dataloader.dataset.data_prefix.pts=${DATAPATH} \
	test_dataloader.dataset.ann_file='sunrgbd_infos_val_mediumvis.pkl' \
	test_dataloader.dataset.pipeline.0.load_dim=8 \
	test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,4,5,6,7]" \
	test_dataloader.dataset.pipeline.2.transforms.2.num_points=50000 \
	test_dataloader.dataset.pipeline.2.transforms.2.firstk_sampling=True \
	model.processed_points=True \



	#model.filter_index=4 \
	#model.post_sort=4 \
	#model.neighbor_score=0.004 \
	#model.updated_fps=0.01 \
	#model.new_fps_strat=True \




#CUDA_VISIBLE_DEVICES=0 python -u demo/pcd_demo.py demo/data/sunrgbd/000017.bin configs/votenet/votenet_8xb16_sunrgbd-3d.py checkpoints/votenet_16x8_sunrgbd-3d-10class_20210820_162823-bf11f014.pth  --show --out-dir outimages_gt --cfg-options test_dataloader.dataset.pipeline.0.use_dim="[0,1,2,3,4,5]"  \


	#test_dataloader.dataset.pipeline.1.transforms.2.num_points=50000 \
	#test_dataloader.dataset.pipeline.1.transforms.2.thresh_sampling=1.0 \



# Change loading.py, dataset config, tools/test.py drawgt flag
