#!/usr/bin/env bash

#SBATCH --partition=research
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=8
#SBATCH --mem=60G
#SBATCH --time=24:0:0

###SBATCH --nodelist=euler141
###SBATCH --exclude=euler09

#SBATCH -o slurm.%j.%N.out # STDOUT
#SBATCH -e slurm.%j.%N.err # STDERR

#SBATCH --job-name=mmdsim
#SBATCH --no-requeue


module load conda/miniforge/23.1.0
bootstrap_conda
conda activate openmmlab

#python -u gen_points.py --method=argmax-filtering-sbr --sbr=1_50 --start 5040 --end 5050 --threshold 0.3 --outfolder_prefix "0.3" & 
#python -u gen_points.py --method=argmax-filtering-sbr --sbr=5_50 --start 5040 --end 5050 --threshold 0.3 --outfolder_prefix "0.3" & 
#python -u gen_points.py --method=argmax-filtering-sbr --sbr=1_100 --start 5040 --end 5050  --threshold 0.3 --outfolder_prefix "0.3" & 
#python -u gen_points.py --method=argmax-filtering-sbr --sbr=5_100 --start 5040 --end 5050  --threshold 0.3 --outfolder_prefix "0.3" & 


python -u gen_points.py --method=argmax-filtering-sbr --sbr=5_1 --start 0 --end 20 --threshold 0.3 --outfolder_prefix "0.3" --dataset "kitti" & 

python -u gen_points.py --method=argmax-filtering-sbr --sbr=5_50 --start 0 --end 20 --threshold 0.3 --outfolder_prefix "0.3" --dataset "kitti" & 

python -u gen_points.py --method=argmax-filtering-sbr --sbr=1_50 --start 0 --end 20 --threshold 0.3 --outfolder_prefix "0.3" --dataset "kitti" & 
wait


