#!/usr/bin/env bash

#SBATCH --array=1-76%10

#SBATCH --partition=research
#SBATCH --cpus-per-task=2
#SBATCH --mem=32G
#SBATCH --time=6:0:0

###SBATCH --nodelist=euler140
#SBATCH --exclude=euler[01-23],euler[28-30]

###SBATCH -o slurm.%j.%N.out # STDOUT
###SBATCH -e slurm.%j.%N.err # STDERR
#SBATCH -o logs/slurm.%A.%a.%N.out
#SBATCH -e logs/slurm.%A.%a.%N.err

#SBATCH --job-name=mmdsim
#SBATCH --no-requeue


module load conda/miniforge/23.1.0
bootstrap_conda
conda activate openmmlab

#START=$1
#END=$2
START=$((($SLURM_ARRAY_TASK_ID-1)*100))
END=$((($SLURM_ARRAY_TASK_ID)*100))
#START=$((($SLURM_ARRAY_TASK_ID-1)*10+1200))
#END=$((($SLURM_ARRAY_TASK_ID)*10+1200))

python -u gen_points.py --method=argmax-filtering-sbr --sbr=1_50 --start $START --end $END --threshold 0.3 --outfolder_prefix "0.3" --dataset "kitti" --split "training"

python -u gen_points.py --method=argmax-filtering-sbr --sbr=1_50 --start $START --end $END --threshold 0.3 --outfolder_prefix "0.3" --dataset "kitti" --split "testing"


