#!/usr/bin/env bash

#SBATCH --array=1-104%1

#SBATCH --partition=research
#SBATCH --cpus-per-task=2
#SBATCH --mem=25G
#SBATCH --time=6:0:0

#SBATCH --nodelist=euler144
###SBATCH --exclude=euler[01-28],euler141,euler142,euler143

###SBATCH -o slurm.%j.%N.out # STDOUT
###SBATCH -e slurm.%j.%N.err # STDERR
#SBATCH -o logs/slurm.%A.%a.%N.out
#SBATCH -e logs/slurm.%A.%a.%N.err

#SBATCH --job-name=mmdsim
#SBATCH --no-requeue


module load anaconda/mini/23.3.1
bootstrap_conda
conda activate openmmlab

#START=$1
#END=$2
START=$((($SLURM_ARRAY_TASK_ID-1)*100))
END=$((($SLURM_ARRAY_TASK_ID)*100))
#START=$((($SLURM_ARRAY_TASK_ID-1)*10+1200))
#END=$((($SLURM_ARRAY_TASK_ID)*10+1200))

python -u getdepth.py --method=gaussfilter-argmax-filtering-sbr --sbr=5_100 --start $START --end $END --threshold 0.048 --outfolder_prefix "0.048"

#--num_peaks 2 --outfolder_prefix "2" 







